basePath: /
definitions:
  helper.SuccessResponse:
    properties:
      code:
        example: 2000
        type: integer
      message:
        example: OK
        type: string
    type: object
  order.OrderCreateRequest:
    properties:
      products:
        items:
          $ref: '#/definitions/order.RequestProducts'
        type: array
    type: object
  order.RequestProducts:
    properties:
      id:
        type: integer
      price:
        type: number
      quantity:
        type: integer
    type: object
  product.ProductInsert:
    properties:
      category_id:
        type: integer
      description:
        type: string
      image:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  users.CreateUser:
    properties:
      address:
        type: string
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
    required:
    - address
    - email
    - firstname
    - lastname
    - password
    type: object
  users.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  users.UserUpdate:
    properties:
      address:
        type: string
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Intern_shopping
  version: "1.0"
paths:
  /admin/user:
    get:
      consumes:
      - application/json
      description: Admin Get all users
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: Admin Get all users
      tags:
      - User
  /api/intern-shop/admin/login:
    post:
      consumes:
      - application/json
      description: SuperAdmin Login
      parameters:
      - description: SuperAdmin login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.Login'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: SuperAdmin Login
      tags:
      - SuperAdmin
  /auth/login:
    post:
      consumes:
      - application/json
      description: User Login
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.Login'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: User Login
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: User Register
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: User Register
      tags:
      - Auth
  /order:
    delete:
      consumes:
      - application/json
      description: User Delete Order
      parameters:
      - description: Order ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: User Delete Order
      tags:
      - Order
    get:
      consumes:
      - application/json
      description: User Get Order Details
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: User Get Order Details
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: Created Product
      parameters:
      - description: Created Product
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/product.ProductInsert'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: Created Product
      tags:
      - Product
  /product:
    get:
      consumes:
      - application/json
      description: User Admin SuperAdmin Get Product
      parameters:
      - description: Product Name
        in: query
        name: pname
        type: string
      - description: Category Name
        in: query
        name: cname
        type: string
      - description: Limit Row
        in: query
        name: limit
        type: integer
      - description: Offset Page
        in: query
        name: page
        type: integer
      - description: sort(ASC / DESC)
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: User Admin SuperAdmin Get Product
      tags:
      - Product
  /user/profile:
    get:
      consumes:
      - application/json
      description: User Get Profile
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: User Get Profile
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Admin Delete category
      parameters:
      - description: Update User Profile
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/users.UserUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: User Update Profile
      tags:
      - User
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
